# Generated by Django 5.2 on 2025-04-11 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_cost_veterinary_care_veterinary_cost'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reproduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mating_records', models.DateField()),
                ('gestation_period', models.IntegerField(default=0, help_text='Gestation period in days')),
                ('estimated_delivery', models.DateField()),
                ('cow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.cow')),
            ],
        ),
    ]
