# Generated by Django 5.2 on 2025-04-11 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_reproduction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reproduction',
            name='estimated_delivery',
        ),
    ]
