# Generated by Django 5.2 on 2025-04-11 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_rename_cost_milk_sales_price_per_litre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manure_sales',
            old_name='cost',
            new_name='price_per_kg',
        ),
    ]
