# Generated by Django 5.2 on 2025-04-11 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_rename_cost_manure_sales_price_per_kg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feed_purchases',
            old_name='cost',
            new_name='price_per_kg',
        ),
    ]
