# Generated by Django 5.2 on 2025-04-11 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_rename_cost_feed_purchases_price_per_kg'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monthlyreport',
            name='veterinary_cost',
        ),
    ]
