# Generated by Django 5.2 on 2025-04-12 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_remove_monthlyreport_veterinary_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='manure_sales',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
