# Generated by Django 5.2 on 2025-04-12 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_manure_sales_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='feed_quantity',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='feed_purchases',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='manure_sales',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='manure_sales',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='milk_sales',
            name='litres',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='milk_sales',
            name='price_per_litre',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='milking_record',
            name='liters',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='veterinary_care',
            name='veterinary_cost',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
