# Generated by Django 5.2 on 2025-04-12 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_feed_feed_quantity_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Immunisation_Records',
        ),
    ]
