# Generated by Django 5.2 on 2025-04-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_rename_cow_cow_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='milking_record',
            old_name='liters',
            new_name='litres',
        ),
    ]
