# Generated by Django 5.2 on 2025-04-28 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_rename_liters_milking_record_litres'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField()),
                ('our_vision', models.CharField()),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField()),
                ('social_handles', models.CharField()),
            ],
        ),
    ]
