# Generated by Django 5.2 on 2025-04-28 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_aboutus'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title',
            field=models.CharField(default='About Us', max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='contact',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='our_vision',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='social_handles',
            field=models.TextField(),
        ),
    ]
