# Generated by Django 5.2 on 2025-04-28 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_aboutus_title_alter_aboutus_contact_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='email',
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='social_handles',
        ),
    ]
