# Generated by Django 5.2 on 2025-04-28 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_remove_aboutus_contact_remove_aboutus_email_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AboutUs',
            new_name='About_Us',
        ),
    ]
